# Generated by Django 3.0.2 on 2020-01-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cachorro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('raca', models.CharField(max_length=20)),
                ('cor', models.CharField(choices=[('PRETO', 'Preto'), ('CARAMELO', 'Caramelo'), ('BRANCO', 'Branco'), ('PARDO', 'Pardo')], max_length=20)),
                ('idade', models.IntegerField()),
            ],
        ),
    ]
