# Generated by Django 3.0.2 on 2020-01-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gato', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nekogirl',
            new_name='Gato',
        ),
    ]
